name: Test
on:
  push:
    branches:
      - 'main'
  pull_request:
env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20

      - name: Install
        run: pnpm install

      - name: Verify build
        run: pnpm build

      - name: Knip
        run: pnpm knip
